export type { IconProps } from "./types";

export { FileIcon } from "./icons/FileIcon";
export { TextIcon } from "./icons/TextIcon";
export { VolumeIcon } from "./icons/VolumeIcon";
export { ArrowCurveLeftUpIcon } from "./icons/ArrowCurveLeftUpIcon";
export { ArrowCurveRightUpIcon } from "./icons/ArrowCurveRightUpIcon";
export { ChevronDoubleLeftIcon } from "./icons/ChevronDoubleLeftIcon";
export { ChevronDownIcon } from "./icons/ChevronDownIcon";
export { CopyRightIcon } from "./icons/CopyRightIcon";
export { StarsIcon } from "./icons/StarsIcon";
export { XIcon } from "./icons/XIcon";
export { MenuIcon } from "./icons/MenuIcon";
export { HomeIcon } from "./icons/HomeIcon";
export { ClockIcon } from "./icons/ClockIcon";
export { ThumbUpIcon } from "./icons/ThumbUpIcon";
export { ThumbDownIcon } from "./icons/ThumbDownIcon";
export { TrashIcon } from "./icons/TrashIcon";
export { DotsVerticalIcon } from "./icons/DotsVerticalIcon";
export { CloseIcon } from "./icons/CloseIcon";
